typedef NS_ENUM(NSUInteger, CTNavigationStep) {
    CTNavigationStepNone,
    CTNavigationStepSearch,
    CTNavigationStepVehicleList,
    CTNavigationStepSelectedVehicle,
    CTNavigationStepInsurance,
    CTNavigationStepDriverDetails,
    CTNavigationStepPaymentWeb,
    CTNavigationStepSavedBooking,
    CTNavigationStepManageBooking,
    CTNavigationStepViewVoucher,
    CTNavigationStepPaymentConfirmation,
    CTNavigationStepWebVehicleList,
    CTNavigationStepProcessingBooking,
};
